### PR TITLE
Bring public crew recruitment up to date with internal page

### PR DESCRIPTION
**Pull request by adamskrz**
### Description

Initially planned to address #567 for the public embed, this PR also addresses #616 (found on the way), as well as copying changes made to the internal page to the public site.

It feels like it might be worth combining the two somehow to prevent them going out of sync like this.

### Checklist

- [x] I accept the contributor license agreement for this repository.
- [x] All active GitHub checks for tests, formatting, and security are passing.
- [x] The correct base branch is being used (if not `main`).
- [x] A GitHub issue is linked to this pull request.

### CODE REVIEW

**Comment by Jbithell** [comment]
Thanks so much for this @adamskrz - looks great and very happy to approve!

Only thought that occured to me was regarding the client names, as these are not currently public. @adam-rms/maintainers, can you recall any reason why we might not have shown client names in public embed/ have any objections to us including them now?

**Comment by cherry-john** [comment]
I think there was previously the idea that a business may not want a list of their active clients available publicly - so it might be nice to make this a setting?

However I don't see a problem with this as is!

**Comment by nathanbillis** [comment]
@Jbithell Only thing I can think of is if a client's name is personally identifiable info e.g. the name of an individual instead of a company, then they might not want to be displayed on the public facing site. As @cherry-john said it might be worth doing it as a setting.

**Comment by adamskrz** [comment]
What would the setting be? Per-client, per vacancy, or globally? 
I feel like its a pretty obscure use-case where you'd want to hide the client but still have the vacancy up on the public site (which can always be unticked).

**Comment by cherry-john** [comment]
@adamskrz I'd say do it at an instance level - ie with the public site settings

That way, it can be disabled if needed for the time of that client's project and re-enabled later

**Comment by adamskrz** [comment]
Added a toggle in the settings

**Review by Jbithell — APPROVED** [review]

**Pull request merged**
