### PR TITLE
202 comment markdown

### LINKED ISSUE #202: [FEATURE] Allow Hyperlinks in comments
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Project Comments should allow hyperlinks so that google spreadsheets can be shared

### Describe the solution you'd like

Hyperlinks in comments

### Describe alternatives you've considered

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cherry-john**
Add markdown renderer to comments so links can be embedded
closes #202 

## Version:

v1

## Checklist:

*Add any outstanding items to this checklist, but don't delete the default options*

- [ ] Updates documentation (if so - is it in this PR, or on the v2 branch?)
- [x] Tested locally

### CODE REVIEW

**Comment by cherry-john** [comment]
There is a small delay when adding a comment now, but it's not significant enough to be annoying :)

**Comment by Jbithell** [comment]
Not really requesting a review, just asking lol

**Comment by Robert-Watts** [comment]
> Approved but not tested

sums 101

**Comment by Jbithell** [comment]
Partially reversed in https://github.com/adam-rms/adam-rms/pull/333

**Pull request merged**
