### PR TITLE
Fix failing root test

### PR DESCRIPTION
**Pull request by chriscn**
Root returns a Pong response rather than Hello World.

## Version
Targeted `v2`

### CODE REVIEW

**Comment by chriscn** [comment]
`package-lock` shouldn't have been committed. Although it allegedly contains a lot of issues.

**Comment by Jbithell** [comment]
> `package-lock` shouldn't have been committed. Although it allegedly contains a lot of issues.

Do you know what the issues are?

**Comment by Jbithell** [comment]
Thanks for this @chriscn. In terms of merging it I'm not sure I'm that keen to merge the lockfile but I'm happy to merge the test change. 

Going forward - changing tests should probably require more than one review actually, wonder if we can get Github to require that for tests only. Changing tests (or "specs") is a breaking change so something we need some tight control of.

**Comment by chriscn** [comment]
Just committed the correct files, @Jbithell - that'll teach me to `git commit -a`.

**Pull request closed without merging**
