### PR TITLE
346 Add Role groups to training modules

### LINKED ISSUE #346: [FEATURE] Limit Training Visibility
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

It would be nice to be able to restrict training modules to certain members so that topics can be written for a smaller group of users

### Describe the solution you'd like

"Limit visibility to" feature like on cms pages and crew roles

### Describe alternatives you've considered

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cherry-john**
By submitting a PR for this repository you accept the contributor license agreement. 

### Description

Adds Limit visibility to Training modules
Training Popup changes

### References

Closes #346 

Documented in adam-rms/website#24

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in the documentation repo
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `main`

### CODE REVIEW

**Comment by cherry-john** [comment]
Need to sort documentation and do wider testing before release ready

**Comment by Jbithell** [comment]
This looks like a WIP - it doesn't validate if the user has permission when they access the module directly

**Review by Jbithell — CHANGES_REQUESTED** [review]
Needs to check permission if accessing directly

**Comment by cherry-john** [comment]
I believe that works with permissions correctly, and have tested with all combinations of permissions. However could do with someone else checking it all works!

**Review by Jbithell — APPROVED** [review]

**Pull request merged**
