### PR TITLE
Locations and Client Archiving

### LINKED ISSUE #396: [FEATURE] Location and Client archiving
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Our instance has a large number of clients and locations, many of which are not used regularly, or were for one off events. 
This clutters our listing of these pages, and makes it more difficult to see actually useful locations and clients.

### Describe the solution you'd like

Archival of Clients and Locations as you can with projects

### Describe alternatives you've considered

Nested locations, but this gets messy on a larger scale

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cherry-john**
By submitting a PR for this repository you accept the contributor license agreement. 

### Description

Adds Location and Client archiving. This is mainly to remove older locations/clients from their relevant listings, and stopping them being assigned to new projects. It does not change calculations for things like client outstanding balance or asset assignments.

image

image

image

image

### References

Closes #396 

Documented in adam-rms/website#32

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in the documentation repo
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `main`

### CODE REVIEW

**Review by Jbithell — APPROVED** [review]

**Comment by Jbithell** [comment]
Is there a reason sub-locations can't be archived?

**Comment by cherry-john** [comment]
Ran into an issue with it when I developed it but just realised what I did wrong.

Probably needs some sort of formatting in the archive section as wont appear if the parent location isn't archived

**Comment by cherry-john** [comment]
@Jbithell Have added sub-location archiving. The archive list ignores location hierarchy as it's the simplest way to manage all the cases of parent/child locations being archived/not archived. 
Happy to take another look if you think this should be included in the archived list.

**Review by Jbithell — DISMISSED** [review]

**Comment by Jbithell** [comment]
@cherry-john this was a headache wasn't it! Gets horrendusly complex for locations that are heavily nested, I think what I've come up with works - but I've not merged in case you want to have a look. Not offended if you don't, feel free to merge.

**Comment by cherry-john** [comment]
Sorry @Jbithell found one more bug!

**Review by Jbithell — APPROVED** [review]

**Pull request merged**
